from .audio import handle_audio as handle_audio
from .file import handle_file as handle_file
from .image import handle_image as handle_image
from .location import handle_location as handle_location
from .reaction import handle_reaction as handle_reaction
from .sticker import handle_sticker as handle_sticker
from .text import handle_text as handle_text
from .unknown import handle_unknown as handle_unknown
from .video import handle_video as handle_video
